- name: Reset Kubernetes
  command: kubeadm reset -f

- name: Join Kubernetes Cluster
  command:
    cmd: > 
      kubeadm join --ignore-preflight-errors=all
      --token {{ hostvars[groups['master'][0]].token.stdout }} 
      {{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}:6443 
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['master'][0]].hash.stdout }}

- name: Poke kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes